name: code checker

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/workflows/**"
      - ".husky/**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".github/workflows/**"
      - ".husky/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true

      - name: Lint
        run: |
          pnpm exec prettier --check .
          cd apps/web
          pnpm exec vite build --config vite.ci.config.ts
          pnpm run lint
          pnpm exec tsc --noEmit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true

      - name: Install Playwright
        run: |
          cd apps/web
          pnpm exec playwright install

      - name: Test
        run: |
          cd apps/web
          pnpm exec vite build --config vite.ci.config.ts
          pnpm run test

  # test-build-docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: s3-image-port

  #     - name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: false
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
